/** Bindings + secrets. `Env` (bindings/vars) is generated by `wrangler types`. */
export interface AppEnv extends Env {
  /** School Basic Auth — also what app users type at onboarding. */
  SCHOOL_USERNAME: string;
  SCHOOL_PASSWORD: string;
  /** Optional grace credential after the school rotates the password. */
  SCHOOL_PASSWORD_PREVIOUS?: string;
  /** Bearer token for /admin/* (manual refresh, status). */
  ADMIN_TOKEN: string;
}

export const RESOURCE_NAMES = ["substitutions", "schedules", "news", "events", "weather"] as const;
export type ResourceName = (typeof RESOURCE_NAMES)[number];

export function isResourceName(s: string): s is ResourceName {
  return (RESOURCE_NAMES as readonly string[]).includes(s);
}
